name: Lint Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter (flake8 on server/)
        run: |
          if [ -d server ]; then
            find server -type f -name "*.py" -print0 | xargs -0 -r flake8
            echo "Python linting was completed successfully."
          else
            echo "server/ directory not found; skipping Python lint."
          fi

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install JSHint (local)
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install jshint

      - name: Run Linter (JSHint on server/database/)
        run: |
          if [ -d server/database ]; then
            # Prefer .jshintrc at repo root; otherwise pass flags for ES syntax + Node
            if [ -f .jshintrc ]; then
              find server/database -type f -name "*.js" -print0 | xargs -0 -r npx jshint
            else
              find server/database -type f -name "*.js" -print0 | xargs -0 -r npx jshint --esversion=8 --node
            fi
            echo "JS linting was completed successfully."
          else
            echo "server/database/ directory not found; skipping JS lint."
          fi
